/* A Bison parser, made by GNU Bison 3.0.4.  */

/* Bison implementation for Yacc-like parsers in C

   Copyright (C) 1984, 1989-1990, 2000-2015 Free Software Foundation, Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <http://www.gnu.org/licenses/>.  */

/* As a special exception, you may create a larger work that contains
   part or all of the Bison parser skeleton and distribute that work
   under terms of your choice, so long as that work isn't itself a
   parser generator using the skeleton or a modified version thereof
   as a parser skeleton.  Alternatively, if you modify or redistribute
   the parser skeleton itself, you may (at your option) remove this
   special exception, which will cause the skeleton and the resulting
   Bison output files to be licensed under the GNU General Public
   License without this special exception.

   This special exception was added by the Free Software Foundation in
   version 2.2 of Bison.  */

/* C LALR(1) parser skeleton written by Richard Stallman, by
   simplifying the original so-called "semantic" parser.  */

/* All symbols defined below should begin with yy or YY, to avoid
   infringing on user name space.  This should be done even for local
   variables, as they might otherwise be expanded by user macros.
   There are some unavoidable exceptions within include files to
   define necessary library symbols; they are noted "INFRINGES ON
   USER NAME SPACE" below.  */

/* Identify Bison output.  */
#define YYBISON 1

/* Bison version.  */
#define YYBISON_VERSION "3.0.4"

/* Skeleton name.  */
#define YYSKELETON_NAME "yacc.c"

/* Pure parsers.  */
#define YYPURE 0

/* Push parsers.  */
#define YYPUSH 0

/* Pull parsers.  */
#define YYPULL 1




/* Copy the first part of user declarations.  */
#line 10 "gpl.y" /* yacc.c:339  */

  
extern int yylex();  // prototype of function generated by flex
extern int yyerror(const char *); // used to print errors
extern int line_count;            // current line in the input; from record.l

#include "error.h"      // class for printing errors (used by gpl)
#include "parser.h"
#include "Table_handler.h"
#include "Expression.h"
#include "Constant.h"
#include "Variable.h"
// add new includes above this line 
#include "gpl_type.h"
#include <iostream>
#include <string>
using namespace std;

template <typename BINOP, Operator_type NM>
Expression* Bin_op_check(Expression* one, Expression* three, unsigned int valid_types)
{
  unsigned int lh_valid = one->type() & valid_types;
  unsigned int rh_valid = three->type() & valid_types;
  if(!lh_valid){
    Error::error(Error::INVALID_LEFT_OPERAND_TYPE, operator_to_string(NM));
  }
  if(!rh_valid){
    Error::error(Error::INVALID_RIGHT_OPERAND_TYPE, operator_to_string(NM));
  }
  if(lh_valid && rh_valid){
    return new BINOP(one, three);
  }
  else
  {
    delete one;
    delete three;
    return new Integer_constant(0);
  }
}

template <typename UNOP, Operator_type NM>
Expression* Un_op_check(Expression* one, unsigned int valid_types){
  
  unsigned int valid = one->type() & valid_types;
  if(!valid){
    Error::error(Error::INVALID_RIGHT_OPERAND_TYPE, operator_to_string(NM));
    delete one;
    return new Integer_constant(0);
  }
  else
    return new UNOP(one);
}


// bison syntax to indicate the end of the header

#line 123 "gpl.tab.c" /* yacc.c:339  */

# ifndef YY_NULLPTR
#  if defined __cplusplus && 201103L <= __cplusplus
#   define YY_NULLPTR nullptr
#  else
#   define YY_NULLPTR 0
#  endif
# endif

/* Enabling verbose error messages.  */
#ifdef YYERROR_VERBOSE
# undef YYERROR_VERBOSE
# define YYERROR_VERBOSE 1
#else
# define YYERROR_VERBOSE 1
#endif

/* In a future release of Bison, this section will be replaced
   by #include "gpl.tab.h".  */
#ifndef YY_YY_GPL_TAB_H_INCLUDED
# define YY_YY_GPL_TAB_H_INCLUDED
/* Debug traces.  */
#ifndef YYDEBUG
# define YYDEBUG 0
#endif
#if YYDEBUG
extern int yydebug;
#endif

/* Token type.  */
#ifndef YYTOKENTYPE
# define YYTOKENTYPE
  enum yytokentype
  {
    T_INT = 258,
    T_DOUBLE = 259,
    T_STRING = 260,
    T_TRIANGLE = 261,
    T_PIXMAP = 262,
    T_CIRCLE = 263,
    T_RECTANGLE = 264,
    T_TEXTBOX = 265,
    T_FORWARD = 266,
    T_INITIALIZATION = 267,
    T_TERMINATION = 268,
    T_TRUE = 269,
    T_FALSE = 270,
    T_TOUCHES = 271,
    T_NEAR = 272,
    T_ANIMATION = 273,
    T_IF = 274,
    T_FOR = 275,
    T_ELSE = 276,
    T_PRINT = 277,
    T_EXIT = 278,
    T_LPAREN = 279,
    T_RPAREN = 280,
    T_LBRACE = 281,
    T_RBRACE = 282,
    T_LBRACKET = 283,
    T_RBRACKET = 284,
    T_SEMIC = 285,
    T_COMMA = 286,
    T_PERIOD = 287,
    T_ASSIGN = 288,
    T_PLUS_ASSIGN = 289,
    T_MINUS_ASSIGN = 290,
    T_PLUS_PLUS = 291,
    T_MINUS_MINUS = 292,
    T_MULTIPLY = 293,
    T_DIVIDE = 294,
    T_MOD = 295,
    T_PLUS = 296,
    T_MINUS = 297,
    T_SIN = 298,
    T_COS = 299,
    T_TAN = 300,
    T_ASIN = 301,
    T_ACOS = 302,
    T_ATAN = 303,
    T_SQRT = 304,
    T_FLOOR = 305,
    T_ABS = 306,
    T_RANDOM = 307,
    T_LESS = 308,
    T_GREATER = 309,
    T_LESS_EQUAL = 310,
    T_GREATER_EQUAL = 311,
    T_EQUAL = 312,
    T_NOT_EQUAL = 313,
    T_AND = 314,
    T_OR = 315,
    T_NOT = 316,
    T_ON = 317,
    T_SPACE = 318,
    T_LEFTARROW = 319,
    T_RIGHTARROW = 320,
    T_UPARROW = 321,
    T_DOWNARROW = 322,
    T_LEFTMOUSE_DOWN = 323,
    T_MIDDLEMOUSE_DOWN = 324,
    T_RIGHTMOUSE_DOWN = 325,
    T_LEFTMOUSE_UP = 326,
    T_MIDDLEMOUSE_UP = 327,
    T_RIGHTMOUSE_UP = 328,
    T_MOUSE_MOVE = 329,
    T_MOUSE_DRAG = 330,
    T_F1 = 331,
    T_AKEY = 332,
    T_SKEY = 333,
    T_DKEY = 334,
    T_FKEY = 335,
    T_HKEY = 336,
    T_JKEY = 337,
    T_KKEY = 338,
    T_LKEY = 339,
    T_WKEY = 340,
    T_ZKEY = 341,
    T_ID = 342,
    T_INT_CONSTANT = 343,
    T_DOUBLE_CONSTANT = 344,
    T_STRING_CONSTANT = 345,
    T_ERROR = 346,
    T_UNARY_OPS = 347,
    T_IF_NO_ELSE = 348
  };
#endif

/* Value type.  */
#if ! defined YYSTYPE && ! defined YYSTYPE_IS_DECLARED

union YYSTYPE
{
#line 68 "gpl.y" /* yacc.c:355  */

 int            union_int;
 std::string*   union_string;  // MUST be a pointer to a string
 double 	union_double;	
 Gpl_type 	union_gpl_type;
 Expression* 	union_expression_ptr;

#line 265 "gpl.tab.c" /* yacc.c:355  */
};

typedef union YYSTYPE YYSTYPE;
# define YYSTYPE_IS_TRIVIAL 1
# define YYSTYPE_IS_DECLARED 1
#endif


extern YYSTYPE yylval;

int yyparse (void);

#endif /* !YY_YY_GPL_TAB_H_INCLUDED  */

/* Copy the second part of user declarations.  */

#line 282 "gpl.tab.c" /* yacc.c:358  */

#ifdef short
# undef short
#endif

#ifdef YYTYPE_UINT8
typedef YYTYPE_UINT8 yytype_uint8;
#else
typedef unsigned char yytype_uint8;
#endif

#ifdef YYTYPE_INT8
typedef YYTYPE_INT8 yytype_int8;
#else
typedef signed char yytype_int8;
#endif

#ifdef YYTYPE_UINT16
typedef YYTYPE_UINT16 yytype_uint16;
#else
typedef unsigned short int yytype_uint16;
#endif

#ifdef YYTYPE_INT16
typedef YYTYPE_INT16 yytype_int16;
#else
typedef short int yytype_int16;
#endif

#ifndef YYSIZE_T
# ifdef __SIZE_TYPE__
#  define YYSIZE_T __SIZE_TYPE__
# elif defined size_t
#  define YYSIZE_T size_t
# elif ! defined YYSIZE_T
#  include <stddef.h> /* INFRINGES ON USER NAME SPACE */
#  define YYSIZE_T size_t
# else
#  define YYSIZE_T unsigned int
# endif
#endif

#define YYSIZE_MAXIMUM ((YYSIZE_T) -1)

#ifndef YY_
# if defined YYENABLE_NLS && YYENABLE_NLS
#  if ENABLE_NLS
#   include <libintl.h> /* INFRINGES ON USER NAME SPACE */
#   define YY_(Msgid) dgettext ("bison-runtime", Msgid)
#  endif
# endif
# ifndef YY_
#  define YY_(Msgid) Msgid
# endif
#endif

#ifndef YY_ATTRIBUTE
# if (defined __GNUC__                                               \
      && (2 < __GNUC__ || (__GNUC__ == 2 && 96 <= __GNUC_MINOR__)))  \
     || defined __SUNPRO_C && 0x5110 <= __SUNPRO_C
#  define YY_ATTRIBUTE(Spec) __attribute__(Spec)
# else
#  define YY_ATTRIBUTE(Spec) /* empty */
# endif
#endif

#ifndef YY_ATTRIBUTE_PURE
# define YY_ATTRIBUTE_PURE   YY_ATTRIBUTE ((__pure__))
#endif

#ifndef YY_ATTRIBUTE_UNUSED
# define YY_ATTRIBUTE_UNUSED YY_ATTRIBUTE ((__unused__))
#endif

#if !defined _Noreturn \
     && (!defined __STDC_VERSION__ || __STDC_VERSION__ < 201112)
# if defined _MSC_VER && 1200 <= _MSC_VER
#  define _Noreturn __declspec (noreturn)
# else
#  define _Noreturn YY_ATTRIBUTE ((__noreturn__))
# endif
#endif

/* Suppress unused-variable warnings by "using" E.  */
#if ! defined lint || defined __GNUC__
# define YYUSE(E) ((void) (E))
#else
# define YYUSE(E) /* empty */
#endif

#if defined __GNUC__ && 407 <= __GNUC__ * 100 + __GNUC_MINOR__
/* Suppress an incorrect diagnostic about yylval being uninitialized.  */
# define YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN \
    _Pragma ("GCC diagnostic push") \
    _Pragma ("GCC diagnostic ignored \"-Wuninitialized\"")\
    _Pragma ("GCC diagnostic ignored \"-Wmaybe-uninitialized\"")
# define YY_IGNORE_MAYBE_UNINITIALIZED_END \
    _Pragma ("GCC diagnostic pop")
#else
# define YY_INITIAL_VALUE(Value) Value
#endif
#ifndef YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
# define YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
# define YY_IGNORE_MAYBE_UNINITIALIZED_END
#endif
#ifndef YY_INITIAL_VALUE
# define YY_INITIAL_VALUE(Value) /* Nothing. */
#endif


#if ! defined yyoverflow || YYERROR_VERBOSE

/* The parser invokes alloca or malloc; define the necessary symbols.  */

# ifdef YYSTACK_USE_ALLOCA
#  if YYSTACK_USE_ALLOCA
#   ifdef __GNUC__
#    define YYSTACK_ALLOC __builtin_alloca
#   elif defined __BUILTIN_VA_ARG_INCR
#    include <alloca.h> /* INFRINGES ON USER NAME SPACE */
#   elif defined _AIX
#    define YYSTACK_ALLOC __alloca
#   elif defined _MSC_VER
#    include <malloc.h> /* INFRINGES ON USER NAME SPACE */
#    define alloca _alloca
#   else
#    define YYSTACK_ALLOC alloca
#    if ! defined _ALLOCA_H && ! defined EXIT_SUCCESS
#     include <stdlib.h> /* INFRINGES ON USER NAME SPACE */
      /* Use EXIT_SUCCESS as a witness for stdlib.h.  */
#     ifndef EXIT_SUCCESS
#      define EXIT_SUCCESS 0
#     endif
#    endif
#   endif
#  endif
# endif

# ifdef YYSTACK_ALLOC
   /* Pacify GCC's 'empty if-body' warning.  */
#  define YYSTACK_FREE(Ptr) do { /* empty */; } while (0)
#  ifndef YYSTACK_ALLOC_MAXIMUM
    /* The OS might guarantee only one guard page at the bottom of the stack,
       and a page size can be as small as 4096 bytes.  So we cannot safely
       invoke alloca (N) if N exceeds 4096.  Use a slightly smaller number
       to allow for a few compiler-allocated temporary stack slots.  */
#   define YYSTACK_ALLOC_MAXIMUM 4032 /* reasonable circa 2006 */
#  endif
# else
#  define YYSTACK_ALLOC YYMALLOC
#  define YYSTACK_FREE YYFREE
#  ifndef YYSTACK_ALLOC_MAXIMUM
#   define YYSTACK_ALLOC_MAXIMUM YYSIZE_MAXIMUM
#  endif
#  if (defined __cplusplus && ! defined EXIT_SUCCESS \
       && ! ((defined YYMALLOC || defined malloc) \
             && (defined YYFREE || defined free)))
#   include <stdlib.h> /* INFRINGES ON USER NAME SPACE */
#   ifndef EXIT_SUCCESS
#    define EXIT_SUCCESS 0
#   endif
#  endif
#  ifndef YYMALLOC
#   define YYMALLOC malloc
#   if ! defined malloc && ! defined EXIT_SUCCESS
void *malloc (YYSIZE_T); /* INFRINGES ON USER NAME SPACE */
#   endif
#  endif
#  ifndef YYFREE
#   define YYFREE free
#   if ! defined free && ! defined EXIT_SUCCESS
void free (void *); /* INFRINGES ON USER NAME SPACE */
#   endif
#  endif
# endif
#endif /* ! defined yyoverflow || YYERROR_VERBOSE */


#if (! defined yyoverflow \
     && (! defined __cplusplus \
         || (defined YYSTYPE_IS_TRIVIAL && YYSTYPE_IS_TRIVIAL)))

/* A type that is properly aligned for any stack member.  */
union yyalloc
{
  yytype_int16 yyss_alloc;
  YYSTYPE yyvs_alloc;
};

/* The size of the maximum gap between one aligned stack and the next.  */
# define YYSTACK_GAP_MAXIMUM (sizeof (union yyalloc) - 1)

/* The size of an array large to enough to hold all stacks, each with
   N elements.  */
# define YYSTACK_BYTES(N) \
     ((N) * (sizeof (yytype_int16) + sizeof (YYSTYPE)) \
      + YYSTACK_GAP_MAXIMUM)

# define YYCOPY_NEEDED 1

/* Relocate STACK from its old location to the new one.  The
   local variables YYSIZE and YYSTACKSIZE give the old and new number of
   elements in the stack, and YYPTR gives the new location of the
   stack.  Advance YYPTR to a properly aligned location for the next
   stack.  */
# define YYSTACK_RELOCATE(Stack_alloc, Stack)                           \
    do                                                                  \
      {                                                                 \
        YYSIZE_T yynewbytes;                                            \
        YYCOPY (&yyptr->Stack_alloc, Stack, yysize);                    \
        Stack = &yyptr->Stack_alloc;                                    \
        yynewbytes = yystacksize * sizeof (*Stack) + YYSTACK_GAP_MAXIMUM; \
        yyptr += yynewbytes / sizeof (*yyptr);                          \
      }                                                                 \
    while (0)

#endif

#if defined YYCOPY_NEEDED && YYCOPY_NEEDED
/* Copy COUNT objects from SRC to DST.  The source and destination do
   not overlap.  */
# ifndef YYCOPY
#  if defined __GNUC__ && 1 < __GNUC__
#   define YYCOPY(Dst, Src, Count) \
      __builtin_memcpy (Dst, Src, (Count) * sizeof (*(Src)))
#  else
#   define YYCOPY(Dst, Src, Count)              \
      do                                        \
        {                                       \
          YYSIZE_T yyi;                         \
          for (yyi = 0; yyi < (Count); yyi++)   \
            (Dst)[yyi] = (Src)[yyi];            \
        }                                       \
      while (0)
#  endif
# endif
#endif /* !YYCOPY_NEEDED */

/* YYFINAL -- State number of the termination state.  */
#define YYFINAL  4
/* YYLAST -- Last index in YYTABLE.  */
#define YYLAST   751

/* YYNTOKENS -- Number of terminals.  */
#define YYNTOKENS  94
/* YYNNTS -- Number of nonterminals.  */
#define YYNNTS  36
/* YYNRULES -- Number of rules.  */
#define YYNRULES  126
/* YYNSTATES -- Number of states.  */
#define YYNSTATES  244

/* YYTRANSLATE[YYX] -- Symbol number corresponding to YYX as returned
   by yylex, with out-of-bounds checking.  */
#define YYUNDEFTOK  2
#define YYMAXUTOK   348

#define YYTRANSLATE(YYX)                                                \
  ((unsigned int) (YYX) <= YYMAXUTOK ? yytranslate[YYX] : YYUNDEFTOK)

/* YYTRANSLATE[TOKEN-NUM] -- Symbol number corresponding to TOKEN-NUM
   as returned by yylex, without out-of-bounds checking.  */
static const yytype_uint8 yytranslate[] =
{
       0,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     1,     2,     3,     4,
       5,     6,     7,     8,     9,    10,    11,    12,    13,    14,
      15,    16,    17,    18,    19,    20,    21,    22,    23,    24,
      25,    26,    27,    28,    29,    30,    31,    32,    33,    34,
      35,    36,    37,    38,    39,    40,    41,    42,    43,    44,
      45,    46,    47,    48,    49,    50,    51,    52,    53,    54,
      55,    56,    57,    58,    59,    60,    61,    62,    63,    64,
      65,    66,    67,    68,    69,    70,    71,    72,    73,    74,
      75,    76,    77,    78,    79,    80,    81,    82,    83,    84,
      85,    86,    87,    88,    89,    90,    91,    92,    93
};

#if YYDEBUG
  /* YYRLINE[YYN] -- Source line where rule number YYN was defined.  */
static const yytype_uint16 yyrline[] =
{
       0,   205,   205,   210,   211,   216,   217,   218,   223,   278,
     347,   348,   349,   354,   355,   360,   361,   366,   367,   368,
     369,   370,   375,   376,   381,   382,   387,   392,   397,   398,
     403,   404,   405,   406,   411,   416,   421,   426,   431,   436,
     441,   442,   443,   444,   445,   446,   447,   448,   449,   450,
     451,   452,   453,   454,   455,   456,   457,   458,   459,   460,
     461,   462,   463,   464,   469,   470,   475,   476,   482,   483,
     488,   489,   490,   491,   492,   497,   498,   503,   508,   513,
     518,   519,   524,   525,   526,   527,   528,   533,   553,   601,
     602,   607,   608,   609,   610,   611,   612,   613,   614,   615,
     616,   617,   618,   619,   630,   641,   642,   643,   644,   645,
     646,   647,   648,   649,   650,   651,   652,   653,   654,   661,
     662,   663,   664,   665,   666,   667,   671
};
#endif

#if YYDEBUG || YYERROR_VERBOSE || 1
/* YYTNAME[SYMBOL-NUM] -- String name of the symbol SYMBOL-NUM.
   First, the terminals, then, starting at YYNTOKENS, nonterminals.  */
static const char *const yytname[] =
{
  "$end", "error", "$undefined", "\"int\"", "\"double\"", "\"string\"",
  "\"triangle\"", "\"pixmap\"", "\"circle\"", "\"rectangle\"",
  "\"textbox\"", "\"forward\"", "\"initialization\"", "\"termination\"",
  "\"true\"", "\"false\"", "\"touches\"", "\"near\"", "\"animation\"",
  "\"if\"", "\"for\"", "\"else\"", "\"print\"", "\"exit\"", "\"(\"",
  "\")\"", "\"{\"", "\"}\"", "\"[\"", "\"]\"", "\";\"", "\",\"", "\".\"",
  "\"=\"", "\"+=\"", "\"-=\"", "\"++\"", "\"--\"", "\"*\"", "\"/\"",
  "\"%\"", "\"+\"", "\"-\"", "\"sin\"", "\"cos\"", "\"tan\"", "\"asin\"",
  "\"acos\"", "\"atan\"", "\"sqrt\"", "\"floor\"", "\"abs\"", "\"random\"",
  "\"<\"", "\">\"", "\"<=\"", "\">=\"", "\"==\"", "\"!=\"", "\"&&\"",
  "\"||\"", "\"!\"", "\"on\"", "\"space\"", "\"leftarrow\"",
  "\"rightarrow\"", "\"uparrow\"", "\"downarrow\"", "\"leftmouse_down\"",
  "\"middlemouse_down\"", "\"rightmouse_down\"", "\"leftmouse_up\"",
  "\"middlemouse_up\"", "\"rightmouse_up\"", "\"mouse_move\"",
  "\"mouse_drag\"", "\"f1\"", "\"akey\"", "\"skey\"", "\"dkey\"",
  "\"fkey\"", "\"hkey\"", "\"jkey\"", "\"kkey\"", "\"lkey\"", "\"wkey\"",
  "\"zkey\"", "\"identifier\"", "\"int constant\"", "\"double constant\"",
  "\"string constant\"", "\"error\"", "T_UNARY_OPS", "T_IF_NO_ELSE",
  "$accept", "program", "declaration_list", "declaration",
  "variable_declaration", "simple_type", "optional_initializer",
  "object_declaration", "object_type", "parameter_list_or_empty",
  "parameter_list", "parameter", "forward_declaration", "block_list",
  "block", "initialization_block", "termination_block", "animation_block",
  "animation_parameter", "check_animation_parameter", "on_block",
  "keystroke", "statement_or_block_of_statements", "statement_block",
  "statement_list", "statement", "if_statement", "for_statement",
  "print_statement", "exit_statement", "assign_statement_or_empty",
  "assign_statement", "variable", "expression", "primary_expression",
  "empty", YY_NULLPTR
};
#endif

# ifdef YYPRINT
/* YYTOKNUM[NUM] -- (External) token number corresponding to the
   (internal) symbol number NUM (which must be that of a token).  */
static const yytype_uint16 yytoknum[] =
{
       0,   256,   257,   258,   259,   260,   261,   262,   263,   264,
     265,   266,   267,   268,   269,   270,   271,   272,   273,   274,
     275,   276,   277,   278,   279,   280,   281,   282,   283,   284,
     285,   286,   287,   288,   289,   290,   291,   292,   293,   294,
     295,   296,   297,   298,   299,   300,   301,   302,   303,   304,
     305,   306,   307,   308,   309,   310,   311,   312,   313,   314,
     315,   316,   317,   318,   319,   320,   321,   322,   323,   324,
     325,   326,   327,   328,   329,   330,   331,   332,   333,   334,
     335,   336,   337,   338,   339,   340,   341,   342,   343,   344,
     345,   346,   347,   348
};
# endif

#define YYPACT_NINF -222

#define yypact_value_is_default(Yystate) \
  (!!((Yystate) == (-222)))

#define YYTABLE_NINF -1

#define yytable_value_is_error(Yytable_value) \
  0

  /* YYPACT[STATE-NUM] -- Index in YYTABLE of the portion describing
     STATE-NUM.  */
static const yytype_int16 yypact[] =
{
    -222,     9,   709,  -222,  -222,  -222,  -222,  -222,  -222,  -222,
    -222,  -222,  -222,    -1,  -222,    -6,   -57,    16,   -40,    24,
      30,  -222,   -28,  -222,    25,  -222,    32,  -222,    36,    36,
     -19,   665,  -222,  -222,  -222,  -222,  -222,    48,   -11,   -11,
    -222,  -222,   -16,   -11,   -12,  -222,  -222,    50,  -222,  -222,
    -222,  -222,  -222,  -222,  -222,  -222,  -222,  -222,  -222,  -222,
    -222,  -222,  -222,  -222,  -222,  -222,  -222,  -222,  -222,  -222,
    -222,  -222,    36,   145,  -222,  -222,   -11,   -11,    56,    57,
      64,    65,    67,    70,    71,    72,   103,   104,   -11,    29,
    -222,  -222,  -222,  -222,   119,  -222,   634,    96,   112,   113,
    -222,  -222,   166,   114,   121,   122,   123,  -222,     0,  -222,
    -222,  -222,   132,   133,   139,   205,   145,  -222,    69,   146,
     193,  -222,   -11,   -11,   -11,   -11,   -11,   -11,   -11,   -11,
     -11,   -11,  -222,   -11,    83,   -11,   -11,  -222,   -11,   -11,
     -11,   -11,   -11,   -11,   -11,   -11,   -11,   -11,   -11,   -11,
     -11,   -11,  -222,   -16,  -222,   -11,    93,   -11,   -11,  -222,
    -222,  -222,  -222,  -222,   -11,   -11,   -11,  -222,  -222,    97,
     162,  -222,  -222,  -222,   220,   247,   274,   301,   328,   355,
     382,   409,   436,   463,   495,  -222,  -222,  -222,    28,    28,
      28,   173,   173,   126,   126,   126,   126,   490,   490,   669,
     642,   634,  -222,   522,   158,  -222,  -222,   549,   576,   634,
     634,   634,  -222,   170,  -222,  -222,  -222,  -222,  -222,  -222,
    -222,  -222,  -222,  -222,   165,    47,   -11,  -222,  -222,     6,
     115,   178,  -222,  -222,   607,    63,  -222,    47,    93,  -222,
    -222,   175,    47,  -222
};

  /* YYDEFACT[STATE-NUM] -- Default reduction number in state STATE-NUM.
     Performed when YYTABLE does not specify something else to do.  Zero
     means the default is an error.  */
static const yytype_uint8 yydefact[] =
{
     126,     0,   126,     4,     1,    10,    11,    12,    17,    18,
      19,    20,    21,     0,     3,     0,     0,     0,     0,     0,
       2,    29,     0,     5,   126,     6,     0,     7,     0,     0,
       0,     0,    28,    30,    31,    32,    33,     0,     0,     0,
       8,    14,   126,     0,     0,    34,    35,     0,    40,    43,
      44,    41,    42,    45,    46,    47,    48,    49,    50,    51,
      52,    63,    53,    54,    55,    56,    57,    58,    59,    60,
      61,    62,     0,     0,   122,   123,     0,     0,     0,     0,
       0,     0,     0,     0,     0,     0,     0,     0,     0,    87,
     121,   124,   125,   120,     0,    91,    13,     0,     0,    22,
      25,    23,     0,     0,     0,     0,     0,    67,     0,    69,
      70,    71,     0,     0,     0,     0,     0,    39,     0,     0,
       0,   105,     0,     0,     0,     0,     0,     0,     0,     0,
       0,     0,   106,     0,     0,     0,     0,     9,     0,     0,
       0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
       0,     0,    15,     0,    16,     0,   126,     0,     0,    66,
      68,    73,    74,    72,     0,     0,     0,    85,    86,     0,
       0,    37,    27,   119,     0,     0,     0,     0,     0,     0,
       0,     0,     0,     0,     0,    89,   118,   117,   102,   103,
     104,   100,   101,    96,    97,    94,    95,    98,    99,    93,
      92,    26,    24,     0,     0,    80,    81,     0,     0,    82,
      83,    84,    38,     0,   107,   108,   109,   110,   111,   112,
     113,   115,   114,   116,    88,     0,     0,    78,    79,     0,
       0,    75,    64,    65,     0,     0,    90,     0,   126,    36,
      76,     0,     0,    77
};

  /* YYPGOTO[NTERM-NUM].  */
static const yytype_int16 yypgoto[] =
{
    -222,  -222,  -222,  -222,  -222,  -222,  -222,  -222,   -61,  -222,
    -222,    61,  -222,  -222,  -222,  -222,  -222,  -222,  -222,  -222,
    -222,  -222,  -221,   -23,   -26,   -43,  -222,  -222,  -222,  -222,
     -22,  -154,   -44,   -25,  -222,   107
};

  /* YYDEFGOTO[NTERM-NUM].  */
static const yytype_int16 yydefgoto[] =
{
      -1,     1,     2,    14,    15,    16,    40,    17,    18,    98,
      99,   100,    19,    20,    32,    33,    34,    35,   119,   170,
      36,    72,   231,   232,   108,   233,   110,   111,   112,   113,
     204,   114,    93,    94,    95,   206
};

  /* YYTABLE[YYPACT[STATE-NUM]] -- What to do in state STATE-NUM.  If
     positive, shift that token.  If negative, reduce the rule whose
     number is the opposite.  If YYTABLE_NINF, syntax error.  */
static const yytype_uint8 yytable[] =
{
     115,   109,   205,    74,    75,    45,    46,   103,   104,     4,
     105,   106,   118,    76,    96,   107,   240,    22,   102,   103,
     104,   243,   105,   106,    23,   103,   104,   159,   105,   106,
      24,    77,    78,    79,    80,    81,    82,    83,    84,    85,
      86,    87,    28,    29,   135,   136,    25,    26,    30,   117,
      88,   120,   121,    38,    27,   169,    42,   133,    39,    37,
      43,   134,    44,   132,   115,   160,   103,   104,    47,   105,
     106,    97,    73,    44,   116,    89,    89,    90,    91,    92,
     122,   123,   103,   104,   205,   105,   106,    89,   124,   125,
     239,   126,    31,    89,   127,   128,   129,   174,   175,   176,
     177,   178,   179,   180,   181,   182,   183,     3,   184,    21,
     186,   187,   115,   188,   189,   190,   191,   192,   193,   194,
     195,   196,   197,   198,   199,   200,   201,   130,   131,   151,
     203,    41,   207,   208,    89,   135,   136,   152,   155,   209,
     210,   211,   135,   136,   153,   156,   157,   158,   137,   101,
      89,     8,     9,    10,    11,    12,   171,   138,   139,   140,
     141,   142,   161,   162,   138,   139,   140,   141,   142,   163,
     185,   172,   143,   144,   145,   146,   147,   148,   149,   150,
      89,   115,   135,   136,   212,   115,   109,   213,   226,   135,
     136,   115,   160,   115,   115,   154,   229,   230,   115,   237,
     242,   234,   236,   235,   138,   139,   140,   141,   142,   135,
     136,   138,   139,   140,   202,     0,   241,     0,   173,   143,
     144,   145,   146,   147,   148,   149,   150,     0,     0,     0,
       0,   138,   139,   140,   141,   142,   135,   136,   164,   165,
     166,   167,   168,     0,     0,   214,   143,   144,   145,   146,
     147,   148,   149,   150,     0,     0,     0,     0,   138,   139,
     140,   141,   142,   135,   136,     0,     0,     0,     0,     0,
       0,     0,   215,   143,   144,   145,   146,   147,   148,   149,
     150,     0,     0,     0,     0,   138,   139,   140,   141,   142,
     135,   136,     0,     0,     0,     0,     0,     0,     0,   216,
     143,   144,   145,   146,   147,   148,   149,   150,     0,     0,
       0,     0,   138,   139,   140,   141,   142,   135,   136,     0,
       0,     0,     0,     0,     0,     0,   217,   143,   144,   145,
     146,   147,   148,   149,   150,     0,     0,     0,     0,   138,
     139,   140,   141,   142,   135,   136,     0,     0,     0,     0,
       0,     0,     0,   218,   143,   144,   145,   146,   147,   148,
     149,   150,     0,     0,     0,     0,   138,   139,   140,   141,
     142,   135,   136,     0,     0,     0,     0,     0,     0,     0,
     219,   143,   144,   145,   146,   147,   148,   149,   150,     0,
       0,     0,     0,   138,   139,   140,   141,   142,   135,   136,
       0,     0,     0,     0,     0,     0,     0,   220,   143,   144,
     145,   146,   147,   148,   149,   150,     0,     0,     0,     0,
     138,   139,   140,   141,   142,   135,   136,     0,     0,     0,
       0,     0,     0,     0,   221,   143,   144,   145,   146,   147,
     148,   149,   150,     0,     0,     0,     0,   138,   139,   140,
     141,   142,   135,   136,     0,     0,     0,     0,     0,     0,
       0,   222,   143,   144,   145,   146,   147,   148,   149,   150,
       0,     0,     0,     0,   138,   139,   140,   141,   142,   135,
     136,     0,     0,     0,     0,     0,     0,     0,   223,   143,
     144,   145,   146,   147,   148,   149,   150,     0,     0,     0,
       0,   138,   139,   140,   141,   142,   135,   136,     0,     0,
       0,   135,   136,     0,     0,     0,   143,   144,   145,   146,
     147,   148,   149,   150,   224,     0,     0,     0,   138,   139,
     140,   141,   142,   138,   139,   140,   141,   142,   135,   136,
       0,     0,     0,   143,   144,   145,   146,   225,   143,   144,
     145,   146,   147,   148,   149,   150,     0,     0,     0,     0,
     138,   139,   140,   141,   142,   135,   136,     0,     0,     0,
       0,     0,     0,     0,   227,   143,   144,   145,   146,   147,
     148,   149,   150,     0,     0,     0,     0,   138,   139,   140,
     141,   142,   135,   136,     0,     0,     0,     0,     0,     0,
       0,   228,   143,   144,   145,   146,   147,   148,   149,   150,
       0,     0,     0,     0,   138,   139,   140,   141,   142,     0,
       0,     0,     0,   135,   136,     0,     0,     0,     0,   143,
     144,   145,   146,   147,   148,   149,   150,   238,     0,     0,
       0,     0,     0,     0,     0,   138,   139,   140,   141,   142,
     135,   136,     0,     0,     0,     0,     0,     0,   135,   136,
     143,   144,   145,   146,   147,   148,   149,   150,     0,     0,
       0,     0,   138,   139,   140,   141,   142,     0,     0,     0,
     138,   139,   140,   141,   142,   135,   136,   143,   144,   145,
     146,   147,   148,   149,   150,   143,   144,   145,   146,   147,
     148,   149,     0,     0,     0,     0,     0,   138,   139,   140,
     141,   142,     5,     6,     7,     8,     9,    10,    11,    12,
      13,     0,   143,   144,   145,   146,   147,   148,    48,    49,
      50,    51,    52,    53,    54,    55,    56,    57,    58,    59,
      60,    61,    62,    63,    64,    65,    66,    67,    68,    69,
      70,    71
};

static const yytype_int16 yycheck[] =
{
      44,    44,   156,    14,    15,    28,    29,    19,    20,     0,
      22,    23,    73,    24,    39,    27,   237,    18,    43,    19,
      20,   242,    22,    23,    30,    19,    20,    27,    22,    23,
      87,    42,    43,    44,    45,    46,    47,    48,    49,    50,
      51,    52,    12,    13,    16,    17,    30,    87,    18,    72,
      61,    76,    77,    28,    30,   116,    24,    28,    33,    87,
      28,    32,    26,    88,   108,   108,    19,    20,    87,    22,
      23,    87,    24,    26,    24,    87,    87,    88,    89,    90,
      24,    24,    19,    20,   238,    22,    23,    87,    24,    24,
      27,    24,    62,    87,    24,    24,    24,   122,   123,   124,
     125,   126,   127,   128,   129,   130,   131,     0,   133,     2,
     135,   136,   156,   138,   139,   140,   141,   142,   143,   144,
     145,   146,   147,   148,   149,   150,   151,    24,    24,    33,
     155,    24,   157,   158,    87,    16,    17,    25,    24,   164,
     165,   166,    16,    17,    31,    24,    24,    24,    29,    42,
      87,     6,     7,     8,     9,    10,    87,    38,    39,    40,
      41,    42,    30,    30,    38,    39,    40,    41,    42,    30,
      87,    25,    53,    54,    55,    56,    57,    58,    59,    60,
      87,   225,    16,    17,    87,   229,   229,    25,    30,    16,
      17,   235,   235,   237,   238,    29,    26,    32,   242,    21,
      25,   226,    87,   229,    38,    39,    40,    41,    42,    16,
      17,    38,    39,    40,   153,    -1,   238,    -1,    25,    53,
      54,    55,    56,    57,    58,    59,    60,    -1,    -1,    -1,
      -1,    38,    39,    40,    41,    42,    16,    17,    33,    34,
      35,    36,    37,    -1,    -1,    25,    53,    54,    55,    56,
      57,    58,    59,    60,    -1,    -1,    -1,    -1,    38,    39,
      40,    41,    42,    16,    17,    -1,    -1,    -1,    -1,    -1,
      -1,    -1,    25,    53,    54,    55,    56,    57,    58,    59,
      60,    -1,    -1,    -1,    -1,    38,    39,    40,    41,    42,
      16,    17,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    25,
      53,    54,    55,    56,    57,    58,    59,    60,    -1,    -1,
      -1,    -1,    38,    39,    40,    41,    42,    16,    17,    -1,
      -1,    -1,    -1,    -1,    -1,    -1,    25,    53,    54,    55,
      56,    57,    58,    59,    60,    -1,    -1,    -1,    -1,    38,
      39,    40,    41,    42,    16,    17,    -1,    -1,    -1,    -1,
      -1,    -1,    -1,    25,    53,    54,    55,    56,    57,    58,
      59,    60,    -1,    -1,    -1,    -1,    38,    39,    40,    41,
      42,    16,    17,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
      25,    53,    54,    55,    56,    57,    58,    59,    60,    -1,
      -1,    -1,    -1,    38,    39,    40,    41,    42,    16,    17,
      -1,    -1,    -1,    -1,    -1,    -1,    -1,    25,    53,    54,
      55,    56,    57,    58,    59,    60,    -1,    -1,    -1,    -1,
      38,    39,    40,    41,    42,    16,    17,    -1,    -1,    -1,
      -1,    -1,    -1,    -1,    25,    53,    54,    55,    56,    57,
      58,    59,    60,    -1,    -1,    -1,    -1,    38,    39,    40,
      41,    42,    16,    17,    -1,    -1,    -1,    -1,    -1,    -1,
      -1,    25,    53,    54,    55,    56,    57,    58,    59,    60,
      -1,    -1,    -1,    -1,    38,    39,    40,    41,    42,    16,
      17,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    25,    53,
      54,    55,    56,    57,    58,    59,    60,    -1,    -1,    -1,
      -1,    38,    39,    40,    41,    42,    16,    17,    -1,    -1,
      -1,    16,    17,    -1,    -1,    -1,    53,    54,    55,    56,
      57,    58,    59,    60,    29,    -1,    -1,    -1,    38,    39,
      40,    41,    42,    38,    39,    40,    41,    42,    16,    17,
      -1,    -1,    -1,    53,    54,    55,    56,    25,    53,    54,
      55,    56,    57,    58,    59,    60,    -1,    -1,    -1,    -1,
      38,    39,    40,    41,    42,    16,    17,    -1,    -1,    -1,
      -1,    -1,    -1,    -1,    25,    53,    54,    55,    56,    57,
      58,    59,    60,    -1,    -1,    -1,    -1,    38,    39,    40,
      41,    42,    16,    17,    -1,    -1,    -1,    -1,    -1,    -1,
      -1,    25,    53,    54,    55,    56,    57,    58,    59,    60,
      -1,    -1,    -1,    -1,    38,    39,    40,    41,    42,    -1,
      -1,    -1,    -1,    16,    17,    -1,    -1,    -1,    -1,    53,
      54,    55,    56,    57,    58,    59,    60,    30,    -1,    -1,
      -1,    -1,    -1,    -1,    -1,    38,    39,    40,    41,    42,
      16,    17,    -1,    -1,    -1,    -1,    -1,    -1,    16,    17,
      53,    54,    55,    56,    57,    58,    59,    60,    -1,    -1,
      -1,    -1,    38,    39,    40,    41,    42,    -1,    -1,    -1,
      38,    39,    40,    41,    42,    16,    17,    53,    54,    55,
      56,    57,    58,    59,    60,    53,    54,    55,    56,    57,
      58,    59,    -1,    -1,    -1,    -1,    -1,    38,    39,    40,
      41,    42,     3,     4,     5,     6,     7,     8,     9,    10,
      11,    -1,    53,    54,    55,    56,    57,    58,    63,    64,
      65,    66,    67,    68,    69,    70,    71,    72,    73,    74,
      75,    76,    77,    78,    79,    80,    81,    82,    83,    84,
      85,    86
};

  /* YYSTOS[STATE-NUM] -- The (internal number of the) accessing
     symbol of state STATE-NUM.  */
static const yytype_uint8 yystos[] =
{
       0,    95,    96,   129,     0,     3,     4,     5,     6,     7,
       8,     9,    10,    11,    97,    98,    99,   101,   102,   106,
     107,   129,    18,    30,    87,    30,    87,    30,    12,    13,
      18,    62,   108,   109,   110,   111,   114,    87,    28,    33,
     100,   129,    24,    28,    26,   117,   117,    87,    63,    64,
      65,    66,    67,    68,    69,    70,    71,    72,    73,    74,
      75,    76,    77,    78,    79,    80,    81,    82,    83,    84,
      85,    86,   115,    24,    14,    15,    24,    42,    43,    44,
      45,    46,    47,    48,    49,    50,    51,    52,    61,    87,
      88,    89,    90,   126,   127,   128,   127,    87,   103,   104,
     105,   129,   127,    19,    20,    22,    23,    27,   118,   119,
     120,   121,   122,   123,   125,   126,    24,   117,   102,   112,
     127,   127,    24,    24,    24,    24,    24,    24,    24,    24,
      24,    24,   127,    28,    32,    16,    17,    29,    38,    39,
      40,    41,    42,    53,    54,    55,    56,    57,    58,    59,
      60,    33,    25,    31,    29,    24,    24,    24,    24,    27,
     119,    30,    30,    30,    33,    34,    35,    36,    37,   102,
     113,    87,    25,    25,   127,   127,   127,   127,   127,   127,
     127,   127,   127,   127,   127,    87,   127,   127,   127,   127,
     127,   127,   127,   127,   127,   127,   127,   127,   127,   127,
     127,   127,   105,   127,   124,   125,   129,   127,   127,   127,
     127,   127,    87,    25,    25,    25,    25,    25,    25,    25,
      25,    25,    25,    25,    29,    25,    30,    25,    25,    26,
      32,   116,   117,   119,   127,   118,    87,    21,    30,    27,
     116,   124,    25,   116
};

  /* YYR1[YYN] -- Symbol number of symbol that rule YYN derives.  */
static const yytype_uint8 yyr1[] =
{
       0,    94,    95,    96,    96,    97,    97,    97,    98,    98,
      99,    99,    99,   100,   100,   101,   101,   102,   102,   102,
     102,   102,   103,   103,   104,   104,   105,   106,   107,   107,
     108,   108,   108,   108,   109,   110,   111,   112,   113,   114,
     115,   115,   115,   115,   115,   115,   115,   115,   115,   115,
     115,   115,   115,   115,   115,   115,   115,   115,   115,   115,
     115,   115,   115,   115,   116,   116,   117,   117,   118,   118,
     119,   119,   119,   119,   119,   120,   120,   121,   122,   123,
     124,   124,   125,   125,   125,   125,   125,   126,   126,   126,
     126,   127,   127,   127,   127,   127,   127,   127,   127,   127,
     127,   127,   127,   127,   127,   127,   127,   127,   127,   127,
     127,   127,   127,   127,   127,   127,   127,   127,   127,   128,
     128,   128,   128,   128,   128,   128,   129
};

  /* YYR2[YYN] -- Number of symbols on the right hand side of rule YYN.  */
static const yytype_uint8 yyr2[] =
{
       0,     2,     2,     2,     1,     2,     2,     2,     3,     5,
       1,     1,     1,     2,     1,     5,     5,     1,     1,     1,
       1,     1,     1,     1,     3,     1,     3,     6,     2,     1,
       1,     1,     1,     1,     2,     2,     8,     2,     2,     3,
       1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
       1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
       1,     1,     1,     1,     1,     1,     3,     2,     2,     1,
       1,     1,     2,     2,     2,     5,     7,     9,     4,     4,
       1,     1,     3,     3,     3,     2,     2,     1,     4,     3,
       6,     1,     3,     3,     3,     3,     3,     3,     3,     3,
       3,     3,     3,     3,     3,     2,     2,     4,     4,     4,
       4,     4,     4,     4,     4,     4,     4,     3,     3,     3,
       1,     1,     1,     1,     1,     1,     0
};


#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (yychar = YYEMPTY)
#define YYEMPTY         (-2)
#define YYEOF           0

#define YYACCEPT        goto yyacceptlab
#define YYABORT         goto yyabortlab
#define YYERROR         goto yyerrorlab


#define YYRECOVERING()  (!!yyerrstatus)

#define YYBACKUP(Token, Value)                                  \
do                                                              \
  if (yychar == YYEMPTY)                                        \
    {                                                           \
      yychar = (Token);                                         \
      yylval = (Value);                                         \
      YYPOPSTACK (yylen);                                       \
      yystate = *yyssp;                                         \
      goto yybackup;                                            \
    }                                                           \
  else                                                          \
    {                                                           \
      yyerror (YY_("syntax error: cannot back up")); \
      YYERROR;                                                  \
    }                                                           \
while (0)

/* Error token number */
#define YYTERROR        1
#define YYERRCODE       256



/* Enable debugging if requested.  */
#if YYDEBUG

# ifndef YYFPRINTF
#  include <stdio.h> /* INFRINGES ON USER NAME SPACE */
#  define YYFPRINTF fprintf
# endif

# define YYDPRINTF(Args)                        \
do {                                            \
  if (yydebug)                                  \
    YYFPRINTF Args;                             \
} while (0)

/* This macro is provided for backward compatibility. */
#ifndef YY_LOCATION_PRINT
# define YY_LOCATION_PRINT(File, Loc) ((void) 0)
#endif


# define YY_SYMBOL_PRINT(Title, Type, Value, Location)                    \
do {                                                                      \
  if (yydebug)                                                            \
    {                                                                     \
      YYFPRINTF (stderr, "%s ", Title);                                   \
      yy_symbol_print (stderr,                                            \
                  Type, Value); \
      YYFPRINTF (stderr, "\n");                                           \
    }                                                                     \
} while (0)


/*----------------------------------------.
| Print this symbol's value on YYOUTPUT.  |
`----------------------------------------*/

static void
yy_symbol_value_print (FILE *yyoutput, int yytype, YYSTYPE const * const yyvaluep)
{
  FILE *yyo = yyoutput;
  YYUSE (yyo);
  if (!yyvaluep)
    return;
# ifdef YYPRINT
  if (yytype < YYNTOKENS)
    YYPRINT (yyoutput, yytoknum[yytype], *yyvaluep);
# endif
  YYUSE (yytype);
}


/*--------------------------------.
| Print this symbol on YYOUTPUT.  |
`--------------------------------*/

static void
yy_symbol_print (FILE *yyoutput, int yytype, YYSTYPE const * const yyvaluep)
{
  YYFPRINTF (yyoutput, "%s %s (",
             yytype < YYNTOKENS ? "token" : "nterm", yytname[yytype]);

  yy_symbol_value_print (yyoutput, yytype, yyvaluep);
  YYFPRINTF (yyoutput, ")");
}

/*------------------------------------------------------------------.
| yy_stack_print -- Print the state stack from its BOTTOM up to its |
| TOP (included).                                                   |
`------------------------------------------------------------------*/

static void
yy_stack_print (yytype_int16 *yybottom, yytype_int16 *yytop)
{
  YYFPRINTF (stderr, "Stack now");
  for (; yybottom <= yytop; yybottom++)
    {
      int yybot = *yybottom;
      YYFPRINTF (stderr, " %d", yybot);
    }
  YYFPRINTF (stderr, "\n");
}

# define YY_STACK_PRINT(Bottom, Top)                            \
do {                                                            \
  if (yydebug)                                                  \
    yy_stack_print ((Bottom), (Top));                           \
} while (0)


/*------------------------------------------------.
| Report that the YYRULE is going to be reduced.  |
`------------------------------------------------*/

static void
yy_reduce_print (yytype_int16 *yyssp, YYSTYPE *yyvsp, int yyrule)
{
  unsigned long int yylno = yyrline[yyrule];
  int yynrhs = yyr2[yyrule];
  int yyi;
  YYFPRINTF (stderr, "Reducing stack by rule %d (line %lu):\n",
             yyrule - 1, yylno);
  /* The symbols being reduced.  */
  for (yyi = 0; yyi < yynrhs; yyi++)
    {
      YYFPRINTF (stderr, "   $%d = ", yyi + 1);
      yy_symbol_print (stderr,
                       yystos[yyssp[yyi + 1 - yynrhs]],
                       &(yyvsp[(yyi + 1) - (yynrhs)])
                                              );
      YYFPRINTF (stderr, "\n");
    }
}

# define YY_REDUCE_PRINT(Rule)          \
do {                                    \
  if (yydebug)                          \
    yy_reduce_print (yyssp, yyvsp, Rule); \
} while (0)

/* Nonzero means print parse trace.  It is left uninitialized so that
   multiple parsers can coexist.  */
int yydebug;
#else /* !YYDEBUG */
# define YYDPRINTF(Args)
# define YY_SYMBOL_PRINT(Title, Type, Value, Location)
# define YY_STACK_PRINT(Bottom, Top)
# define YY_REDUCE_PRINT(Rule)
#endif /* !YYDEBUG */


/* YYINITDEPTH -- initial size of the parser's stacks.  */
#ifndef YYINITDEPTH
# define YYINITDEPTH 200
#endif

/* YYMAXDEPTH -- maximum size the stacks can grow to (effective only
   if the built-in stack extension method is used).

   Do not make this value too large; the results are undefined if
   YYSTACK_ALLOC_MAXIMUM < YYSTACK_BYTES (YYMAXDEPTH)
   evaluated with infinite-precision integer arithmetic.  */

#ifndef YYMAXDEPTH
# define YYMAXDEPTH 10000
#endif


#if YYERROR_VERBOSE

# ifndef yystrlen
#  if defined __GLIBC__ && defined _STRING_H
#   define yystrlen strlen
#  else
/* Return the length of YYSTR.  */
static YYSIZE_T
yystrlen (const char *yystr)
{
  YYSIZE_T yylen;
  for (yylen = 0; yystr[yylen]; yylen++)
    continue;
  return yylen;
}
#  endif
# endif

# ifndef yystpcpy
#  if defined __GLIBC__ && defined _STRING_H && defined _GNU_SOURCE
#   define yystpcpy stpcpy
#  else
/* Copy YYSRC to YYDEST, returning the address of the terminating '\0' in
   YYDEST.  */
static char *
yystpcpy (char *yydest, const char *yysrc)
{
  char *yyd = yydest;
  const char *yys = yysrc;

  while ((*yyd++ = *yys++) != '\0')
    continue;

  return yyd - 1;
}
#  endif
# endif

# ifndef yytnamerr
/* Copy to YYRES the contents of YYSTR after stripping away unnecessary
   quotes and backslashes, so that it's suitable for yyerror.  The
   heuristic is that double-quoting is unnecessary unless the string
   contains an apostrophe, a comma, or backslash (other than
   backslash-backslash).  YYSTR is taken from yytname.  If YYRES is
   null, do not copy; instead, return the length of what the result
   would have been.  */
static YYSIZE_T
yytnamerr (char *yyres, const char *yystr)
{
  if (*yystr == '"')
    {
      YYSIZE_T yyn = 0;
      char const *yyp = yystr;

      for (;;)
        switch (*++yyp)
          {
          case '\'':
          case ',':
            goto do_not_strip_quotes;

          case '\\':
            if (*++yyp != '\\')
              goto do_not_strip_quotes;
            /* Fall through.  */
          default:
            if (yyres)
              yyres[yyn] = *yyp;
            yyn++;
            break;

          case '"':
            if (yyres)
              yyres[yyn] = '\0';
            return yyn;
          }
    do_not_strip_quotes: ;
    }

  if (! yyres)
    return yystrlen (yystr);

  return yystpcpy (yyres, yystr) - yyres;
}
# endif

/* Copy into *YYMSG, which is of size *YYMSG_ALLOC, an error message
   about the unexpected token YYTOKEN for the state stack whose top is
   YYSSP.

   Return 0 if *YYMSG was successfully written.  Return 1 if *YYMSG is
   not large enough to hold the message.  In that case, also set
   *YYMSG_ALLOC to the required number of bytes.  Return 2 if the
   required number of bytes is too large to store.  */
static int
yysyntax_error (YYSIZE_T *yymsg_alloc, char **yymsg,
                yytype_int16 *yyssp, int yytoken)
{
  YYSIZE_T yysize0 = yytnamerr (YY_NULLPTR, yytname[yytoken]);
  YYSIZE_T yysize = yysize0;
  enum { YYERROR_VERBOSE_ARGS_MAXIMUM = 5 };
  /* Internationalized format string. */
  const char *yyformat = YY_NULLPTR;
  /* Arguments of yyformat. */
  char const *yyarg[YYERROR_VERBOSE_ARGS_MAXIMUM];
  /* Number of reported tokens (one for the "unexpected", one per
     "expected"). */
  int yycount = 0;

  /* There are many possibilities here to consider:
     - If this state is a consistent state with a default action, then
       the only way this function was invoked is if the default action
       is an error action.  In that case, don't check for expected
       tokens because there are none.
     - The only way there can be no lookahead present (in yychar) is if
       this state is a consistent state with a default action.  Thus,
       detecting the absence of a lookahead is sufficient to determine
       that there is no unexpected or expected token to report.  In that
       case, just report a simple "syntax error".
     - Don't assume there isn't a lookahead just because this state is a
       consistent state with a default action.  There might have been a
       previous inconsistent state, consistent state with a non-default
       action, or user semantic action that manipulated yychar.
     - Of course, the expected token list depends on states to have
       correct lookahead information, and it depends on the parser not
       to perform extra reductions after fetching a lookahead from the
       scanner and before detecting a syntax error.  Thus, state merging
       (from LALR or IELR) and default reductions corrupt the expected
       token list.  However, the list is correct for canonical LR with
       one exception: it will still contain any token that will not be
       accepted due to an error action in a later state.
  */
  if (yytoken != YYEMPTY)
    {
      int yyn = yypact[*yyssp];
      yyarg[yycount++] = yytname[yytoken];
      if (!yypact_value_is_default (yyn))
        {
          /* Start YYX at -YYN if negative to avoid negative indexes in
             YYCHECK.  In other words, skip the first -YYN actions for
             this state because they are default actions.  */
          int yyxbegin = yyn < 0 ? -yyn : 0;
          /* Stay within bounds of both yycheck and yytname.  */
          int yychecklim = YYLAST - yyn + 1;
          int yyxend = yychecklim < YYNTOKENS ? yychecklim : YYNTOKENS;
          int yyx;

          for (yyx = yyxbegin; yyx < yyxend; ++yyx)
            if (yycheck[yyx + yyn] == yyx && yyx != YYTERROR
                && !yytable_value_is_error (yytable[yyx + yyn]))
              {
                if (yycount == YYERROR_VERBOSE_ARGS_MAXIMUM)
                  {
                    yycount = 1;
                    yysize = yysize0;
                    break;
                  }
                yyarg[yycount++] = yytname[yyx];
                {
                  YYSIZE_T yysize1 = yysize + yytnamerr (YY_NULLPTR, yytname[yyx]);
                  if (! (yysize <= yysize1
                         && yysize1 <= YYSTACK_ALLOC_MAXIMUM))
                    return 2;
                  yysize = yysize1;
                }
              }
        }
    }

  switch (yycount)
    {
# define YYCASE_(N, S)                      \
      case N:                               \
        yyformat = S;                       \
      break
      YYCASE_(0, YY_("syntax error"));
      YYCASE_(1, YY_("syntax error, unexpected %s"));
      YYCASE_(2, YY_("syntax error, unexpected %s, expecting %s"));
      YYCASE_(3, YY_("syntax error, unexpected %s, expecting %s or %s"));
      YYCASE_(4, YY_("syntax error, unexpected %s, expecting %s or %s or %s"));
      YYCASE_(5, YY_("syntax error, unexpected %s, expecting %s or %s or %s or %s"));
# undef YYCASE_
    }

  {
    YYSIZE_T yysize1 = yysize + yystrlen (yyformat);
    if (! (yysize <= yysize1 && yysize1 <= YYSTACK_ALLOC_MAXIMUM))
      return 2;
    yysize = yysize1;
  }

  if (*yymsg_alloc < yysize)
    {
      *yymsg_alloc = 2 * yysize;
      if (! (yysize <= *yymsg_alloc
             && *yymsg_alloc <= YYSTACK_ALLOC_MAXIMUM))
        *yymsg_alloc = YYSTACK_ALLOC_MAXIMUM;
      return 1;
    }

  /* Avoid sprintf, as that infringes on the user's name space.
     Don't have undefined behavior even if the translation
     produced a string with the wrong number of "%s"s.  */
  {
    char *yyp = *yymsg;
    int yyi = 0;
    while ((*yyp = *yyformat) != '\0')
      if (*yyp == '%' && yyformat[1] == 's' && yyi < yycount)
        {
          yyp += yytnamerr (yyp, yyarg[yyi++]);
          yyformat += 2;
        }
      else
        {
          yyp++;
          yyformat++;
        }
  }
  return 0;
}
#endif /* YYERROR_VERBOSE */

/*-----------------------------------------------.
| Release the memory associated to this symbol.  |
`-----------------------------------------------*/

static void
yydestruct (const char *yymsg, int yytype, YYSTYPE *yyvaluep)
{
  YYUSE (yyvaluep);
  if (!yymsg)
    yymsg = "Deleting";
  YY_SYMBOL_PRINT (yymsg, yytype, yyvaluep, yylocationp);

  YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
  switch (yytype)
    {
          case 87: /* "identifier"  */
#line 75 "gpl.y" /* yacc.c:1257  */
      {delete ((*yyvaluep).union_string);}
#line 1403 "gpl.tab.c" /* yacc.c:1257  */
        break;

    case 90: /* "string constant"  */
#line 75 "gpl.y" /* yacc.c:1257  */
      {delete ((*yyvaluep).union_string);}
#line 1409 "gpl.tab.c" /* yacc.c:1257  */
        break;


      default:
        break;
    }
  YY_IGNORE_MAYBE_UNINITIALIZED_END
}




/* The lookahead symbol.  */
int yychar;

/* The semantic value of the lookahead symbol.  */
YYSTYPE yylval;
/* Number of syntax errors so far.  */
int yynerrs;


/*----------.
| yyparse.  |
`----------*/

int
yyparse (void)
{
    int yystate;
    /* Number of tokens to shift before error messages enabled.  */
    int yyerrstatus;

    /* The stacks and their tools:
       'yyss': related to states.
       'yyvs': related to semantic values.

       Refer to the stacks through separate pointers, to allow yyoverflow
       to reallocate them elsewhere.  */

    /* The state stack.  */
    yytype_int16 yyssa[YYINITDEPTH];
    yytype_int16 *yyss;
    yytype_int16 *yyssp;

    /* The semantic value stack.  */
    YYSTYPE yyvsa[YYINITDEPTH];
    YYSTYPE *yyvs;
    YYSTYPE *yyvsp;

    YYSIZE_T yystacksize;

  int yyn;
  int yyresult;
  /* Lookahead token as an internal (translated) token number.  */
  int yytoken = 0;
  /* The variables used to return semantic value and location from the
     action routines.  */
  YYSTYPE yyval;

#if YYERROR_VERBOSE
  /* Buffer for error messages, and its allocated size.  */
  char yymsgbuf[128];
  char *yymsg = yymsgbuf;
  YYSIZE_T yymsg_alloc = sizeof yymsgbuf;
#endif

#define YYPOPSTACK(N)   (yyvsp -= (N), yyssp -= (N))

  /* The number of symbols on the RHS of the reduced rule.
     Keep to zero when no symbol should be popped.  */
  int yylen = 0;

  yyssp = yyss = yyssa;
  yyvsp = yyvs = yyvsa;
  yystacksize = YYINITDEPTH;

  YYDPRINTF ((stderr, "Starting parse\n"));

  yystate = 0;
  yyerrstatus = 0;
  yynerrs = 0;
  yychar = YYEMPTY; /* Cause a token to be read.  */
  goto yysetstate;

/*------------------------------------------------------------.
| yynewstate -- Push a new state, which is found in yystate.  |
`------------------------------------------------------------*/
 yynewstate:
  /* In all cases, when you get here, the value and location stacks
     have just been pushed.  So pushing a state here evens the stacks.  */
  yyssp++;

 yysetstate:
  *yyssp = yystate;

  if (yyss + yystacksize - 1 <= yyssp)
    {
      /* Get the current used size of the three stacks, in elements.  */
      YYSIZE_T yysize = yyssp - yyss + 1;

#ifdef yyoverflow
      {
        /* Give user a chance to reallocate the stack.  Use copies of
           these so that the &'s don't force the real ones into
           memory.  */
        YYSTYPE *yyvs1 = yyvs;
        yytype_int16 *yyss1 = yyss;

        /* Each stack pointer address is followed by the size of the
           data in use in that stack, in bytes.  This used to be a
           conditional around just the two extra args, but that might
           be undefined if yyoverflow is a macro.  */
        yyoverflow (YY_("memory exhausted"),
                    &yyss1, yysize * sizeof (*yyssp),
                    &yyvs1, yysize * sizeof (*yyvsp),
                    &yystacksize);

        yyss = yyss1;
        yyvs = yyvs1;
      }
#else /* no yyoverflow */
# ifndef YYSTACK_RELOCATE
      goto yyexhaustedlab;
# else
      /* Extend the stack our own way.  */
      if (YYMAXDEPTH <= yystacksize)
        goto yyexhaustedlab;
      yystacksize *= 2;
      if (YYMAXDEPTH < yystacksize)
        yystacksize = YYMAXDEPTH;

      {
        yytype_int16 *yyss1 = yyss;
        union yyalloc *yyptr =
          (union yyalloc *) YYSTACK_ALLOC (YYSTACK_BYTES (yystacksize));
        if (! yyptr)
          goto yyexhaustedlab;
        YYSTACK_RELOCATE (yyss_alloc, yyss);
        YYSTACK_RELOCATE (yyvs_alloc, yyvs);
#  undef YYSTACK_RELOCATE
        if (yyss1 != yyssa)
          YYSTACK_FREE (yyss1);
      }
# endif
#endif /* no yyoverflow */

      yyssp = yyss + yysize - 1;
      yyvsp = yyvs + yysize - 1;

      YYDPRINTF ((stderr, "Stack size increased to %lu\n",
                  (unsigned long int) yystacksize));

      if (yyss + yystacksize - 1 <= yyssp)
        YYABORT;
    }

  YYDPRINTF ((stderr, "Entering state %d\n", yystate));

  if (yystate == YYFINAL)
    YYACCEPT;

  goto yybackup;

/*-----------.
| yybackup.  |
`-----------*/
yybackup:

  /* Do appropriate processing given the current state.  Read a
     lookahead token if we need one and don't already have one.  */

  /* First try to decide what to do without reference to lookahead token.  */
  yyn = yypact[yystate];
  if (yypact_value_is_default (yyn))
    goto yydefault;

  /* Not known => get a lookahead token if don't already have one.  */

  /* YYCHAR is either YYEMPTY or YYEOF or a valid lookahead symbol.  */
  if (yychar == YYEMPTY)
    {
      YYDPRINTF ((stderr, "Reading a token: "));
      yychar = yylex ();
    }

  if (yychar <= YYEOF)
    {
      yychar = yytoken = YYEOF;
      YYDPRINTF ((stderr, "Now at end of input.\n"));
    }
  else
    {
      yytoken = YYTRANSLATE (yychar);
      YY_SYMBOL_PRINT ("Next token is", yytoken, &yylval, &yylloc);
    }

  /* If the proper action on seeing token YYTOKEN is to reduce or to
     detect an error, take that action.  */
  yyn += yytoken;
  if (yyn < 0 || YYLAST < yyn || yycheck[yyn] != yytoken)
    goto yydefault;
  yyn = yytable[yyn];
  if (yyn <= 0)
    {
      if (yytable_value_is_error (yyn))
        goto yyerrlab;
      yyn = -yyn;
      goto yyreduce;
    }

  /* Count tokens shifted since error; after three, turn off error
     status.  */
  if (yyerrstatus)
    yyerrstatus--;

  /* Shift the lookahead token.  */
  YY_SYMBOL_PRINT ("Shifting", yytoken, &yylval, &yylloc);

  /* Discard the shifted token.  */
  yychar = YYEMPTY;

  yystate = yyn;
  YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
  *++yyvsp = yylval;
  YY_IGNORE_MAYBE_UNINITIALIZED_END

  goto yynewstate;


/*-----------------------------------------------------------.
| yydefault -- do the default action for the current state.  |
`-----------------------------------------------------------*/
yydefault:
  yyn = yydefact[yystate];
  if (yyn == 0)
    goto yyerrlab;
  goto yyreduce;


/*-----------------------------.
| yyreduce -- Do a reduction.  |
`-----------------------------*/
yyreduce:
  /* yyn is the number of a rule to reduce with.  */
  yylen = yyr2[yyn];

  /* If YYLEN is nonzero, implement the default value of the action:
     '$$ = $1'.

     Otherwise, the following line sets YYVAL to garbage.
     This behavior is undocumented and Bison
     users should not rely upon it.  Assigning to YYVAL
     unconditionally makes the parser a bit smaller, and it avoids a
     GCC warning that YYVAL may be used uninitialized.  */
  yyval = yyvsp[1-yylen];


  YY_REDUCE_PRINT (yyn);
  switch (yyn)
    {
        case 8:
#line 224 "gpl.y" /* yacc.c:1646  */
    {
      Table_handler& th = Table_handler::instance();
      Expression* eptr = (yyvsp[0].union_expression_ptr);
      Constant* cptr = (eptr==nullptr ? nullptr: eptr->evaluate());
      std::shared_ptr<Symbol> sym;
      switch((yyvsp[-2].union_gpl_type)){
        case INT:
	      {
	        int val;
	        try{
	          val=(cptr==nullptr)? 0 : cptr->as_int();
	        }
	        catch(Gpl_type thrown){
            Error::error(Error::INVALID_TYPE_FOR_INITIAL_VALUE, gpl_type_to_string(thrown), *(yyvsp[-1].union_string), "int");
          }
	        sym = std::make_shared<Symbol>(*(yyvsp[-1].union_string), new int(val));
	        break;
        }
	      case DOUBLE:
	      {
	        double val;
	        try{
            val=(cptr==nullptr)? 0.0 : cptr->as_double();
	        }
          catch(Gpl_type thrown){
            Error::error(Error::INVALID_TYPE_FOR_INITIAL_VALUE, gpl_type_to_string(thrown), *(yyvsp[-1].union_string), "double");
          }
          sym = std::make_shared<Symbol>(*(yyvsp[-1].union_string), new double(val));
	        break;
	      }
	      case STRING:
	      {
	        string val;
	        try{
            val=(cptr==nullptr)? "" : cptr->as_string();
	        }
          catch(Gpl_type thrown){
            Error::error(Error::INVALID_TYPE_FOR_INITIAL_VALUE, gpl_type_to_string(thrown), *(yyvsp[-1].union_string), "string");
          }
          sym = std::make_shared<Symbol>(*(yyvsp[-1].union_string), new std::string(val));
	        break;
	      }
      }
      if(th.defined_in_current_scope(*(yyvsp[-1].union_string)))
      {
	      Error::error(Error::PREVIOUSLY_DECLARED_VARIABLE, *(yyvsp[-1].union_string));
	      delete (yyvsp[-1].union_string);
        delete (yyvsp[0].union_expression_ptr);
        break;
      }
      th.insert(sym);
      delete (yyvsp[-1].union_string);
      delete (yyvsp[0].union_expression_ptr);
    }
#line 1726 "gpl.tab.c" /* yacc.c:1646  */
    break;

  case 9:
#line 279 "gpl.y" /* yacc.c:1646  */
    {
      Table_handler& th = Table_handler::instance();
      int index = 0;
      try{
        index = (yyvsp[-1].union_expression_ptr)->evaluate()->as_int();
      }catch(Gpl_type thrown){
        switch(thrown){
          case DOUBLE:
          {
            Error::error(Error::ARRAY_SIZE_MUST_BE_AN_INTEGER, "double", *(yyvsp[-3].union_string));
            break;
          }
          case STRING:
          {
            Error::error(Error::ARRAY_SIZE_MUST_BE_AN_INTEGER, "string", *(yyvsp[-3].union_string));
            break;
          }
        }
        delete (yyvsp[-3].union_string);
        delete (yyvsp[-1].union_expression_ptr);
        break;
      }
      if(index < 1) {
        Error::error(Error::INVALID_ARRAY_SIZE, *(yyvsp[-3].union_string), (yyvsp[-1].union_expression_ptr)->evaluate()->as_string());
        index=1;
      }
      std::shared_ptr<Symbol> sym;
      switch((yyvsp[-4].union_gpl_type)){
	      case INT:
	      {
	        int* test = new int[index];
          for(int i = 0; i < index; i++)
	          test[i] = 0;
	        sym = std::make_shared<Symbol>(*(yyvsp[-3].union_string), test, index);
	        break;
	      }
        case DOUBLE:
	      {
          double* test = new double[index];
	        for(int i = 0; i < index; i++)
	        test[i] = 0.0;
	        sym = std::make_shared<Symbol>(*(yyvsp[-3].union_string), test, index);
      	  break;
	      } 
	      case STRING:
	      {
	        std::string* test = new std::string[index];
	        for(int i = 0; i < index; i++)
	          test[i] = "";
	        sym = std::make_shared<Symbol>(*(yyvsp[-3].union_string), test, index);
	        break;
	      }
      }
      if(th.defined_in_current_scope(*(yyvsp[-3].union_string)))
      {
	      Error::error(Error::PREVIOUSLY_DECLARED_VARIABLE, *(yyvsp[-3].union_string));
	      delete (yyvsp[-3].union_string);
	      delete (yyvsp[-1].union_expression_ptr);
        break;
      }
      th.insert(sym);
      delete (yyvsp[-3].union_string);
      delete (yyvsp[-1].union_expression_ptr);
    }
#line 1795 "gpl.tab.c" /* yacc.c:1646  */
    break;

  case 10:
#line 347 "gpl.y" /* yacc.c:1646  */
    {(yyval.union_gpl_type)=INT;}
#line 1801 "gpl.tab.c" /* yacc.c:1646  */
    break;

  case 11:
#line 348 "gpl.y" /* yacc.c:1646  */
    {(yyval.union_gpl_type)=DOUBLE;}
#line 1807 "gpl.tab.c" /* yacc.c:1646  */
    break;

  case 12:
#line 349 "gpl.y" /* yacc.c:1646  */
    {(yyval.union_gpl_type)=STRING;}
#line 1813 "gpl.tab.c" /* yacc.c:1646  */
    break;

  case 13:
#line 354 "gpl.y" /* yacc.c:1646  */
    {(yyval.union_expression_ptr)=(yyvsp[0].union_expression_ptr);}
#line 1819 "gpl.tab.c" /* yacc.c:1646  */
    break;

  case 14:
#line 355 "gpl.y" /* yacc.c:1646  */
    {(yyval.union_expression_ptr)=nullptr;}
#line 1825 "gpl.tab.c" /* yacc.c:1646  */
    break;

  case 15:
#line 360 "gpl.y" /* yacc.c:1646  */
    {(yyvsp[-3].union_string); /*change*/}
#line 1831 "gpl.tab.c" /* yacc.c:1646  */
    break;

  case 16:
#line 361 "gpl.y" /* yacc.c:1646  */
    {(yyvsp[-3].union_string); /*change*/}
#line 1837 "gpl.tab.c" /* yacc.c:1646  */
    break;

  case 27:
#line 392 "gpl.y" /* yacc.c:1646  */
    {(yyvsp[-3].union_string); /*CHANGE*/}
#line 1843 "gpl.tab.c" /* yacc.c:1646  */
    break;

  case 36:
#line 421 "gpl.y" /* yacc.c:1646  */
    {(yyvsp[-6].union_string); /*CHANGE*/}
#line 1849 "gpl.tab.c" /* yacc.c:1646  */
    break;

  case 37:
#line 426 "gpl.y" /* yacc.c:1646  */
    {(yyvsp[0].union_string); /*CHANGE*/}
#line 1855 "gpl.tab.c" /* yacc.c:1646  */
    break;

  case 38:
#line 431 "gpl.y" /* yacc.c:1646  */
    {(yyvsp[0].union_string); /*CHANGE*/}
#line 1861 "gpl.tab.c" /* yacc.c:1646  */
    break;

  case 87:
#line 534 "gpl.y" /* yacc.c:1646  */
    {
      Table_handler& th = Table_handler::instance();
      if(!th.defined_in_current_scope(*(yyvsp[0].union_string)))
      {
	      Error::error(Error::UNDECLARED_VARIABLE, *(yyvsp[0].union_string));
	      delete (yyvsp[0].union_string);
        (yyval.union_expression_ptr) = new Integer_constant(0);
      	break;
      }
      std::shared_ptr<Symbol> matching = th.lookup(*(yyvsp[0].union_string));
      if(matching->is_array()){
        Error::error(Error::VARIABLE_IS_AN_ARRAY, *(yyvsp[0].union_string));
        delete (yyvsp[0].union_string);
        (yyval.union_expression_ptr) = new Integer_constant(0);
        break;
      }
      (yyval.union_expression_ptr) = new Variable(matching);
      delete (yyvsp[0].union_string);
    }
#line 1885 "gpl.tab.c" /* yacc.c:1646  */
    break;

  case 88:
#line 554 "gpl.y" /* yacc.c:1646  */
    { 
      //get table handler, lookup symbol $3 and only execute next line if it's there
      Table_handler& th = Table_handler::instance();
      if(!th.defined_in_current_scope(*(yyvsp[-3].union_string)))
      {
	      Error::error(Error::UNDECLARED_VARIABLE, *(yyvsp[-3].union_string)+"[]");
	      delete (yyvsp[-3].union_string);
        delete (yyvsp[-1].union_expression_ptr);
        (yyval.union_expression_ptr) = new Integer_constant(0);
        break;
      }
      std::shared_ptr<Symbol> matching = th.lookup(*(yyvsp[-3].union_string));
      //if the symbol is not an array, throw an error
      if(!matching->is_array()){
        Error::error(Error::VARIABLE_NOT_AN_ARRAY, *(yyvsp[-3].union_string));
        delete (yyvsp[-3].union_string);
        delete (yyvsp[-1].union_expression_ptr);
        (yyval.union_expression_ptr) = new Integer_constant(0);
        break;
      }
      Expression* expr = (yyvsp[-1].union_expression_ptr);
      switch(expr->type()){
        case DOUBLE:
          Error::error(Error::ARRAY_INDEX_MUST_BE_AN_INTEGER, *(yyvsp[-3].union_string), "A double expression");
          delete (yyvsp[-1].union_expression_ptr);
          expr = new Integer_constant(0);
          break;
        case STRING:
          Error::error(Error::ARRAY_INDEX_MUST_BE_AN_INTEGER, *(yyvsp[-3].union_string), "A string expression");
          delete (yyvsp[-1].union_expression_ptr);
          expr = new Integer_constant(0);
          break;
        case ANIMATION_BLOCK:
          Error::error(Error::ARRAY_INDEX_MUST_BE_AN_INTEGER, *(yyvsp[-3].union_string), "An animation_block expression");
          delete (yyvsp[-1].union_expression_ptr);
          expr = new Integer_constant(0);
          break;
        case INT:
          break;
        default:
          //assert(false);
          std::cerr << "bad happen 12312\n";
      }
      (yyval.union_expression_ptr) = new Variable(matching, expr);
      delete (yyvsp[-3].union_string);
      //delete $3;
    }
#line 1937 "gpl.tab.c" /* yacc.c:1646  */
    break;

  case 89:
#line 601 "gpl.y" /* yacc.c:1646  */
    {(yyvsp[-2].union_string); (yyvsp[0].union_string); /*CHANGE*/}
#line 1943 "gpl.tab.c" /* yacc.c:1646  */
    break;

  case 90:
#line 602 "gpl.y" /* yacc.c:1646  */
    {(yyvsp[-5].union_string); (yyvsp[0].union_string); /*CHANGE*/}
#line 1949 "gpl.tab.c" /* yacc.c:1646  */
    break;

  case 91:
#line 607 "gpl.y" /* yacc.c:1646  */
    {(yyval.union_expression_ptr)=(yyvsp[0].union_expression_ptr);}
#line 1955 "gpl.tab.c" /* yacc.c:1646  */
    break;

  case 92:
#line 608 "gpl.y" /* yacc.c:1646  */
    {(yyval.union_expression_ptr) = Bin_op_check<Or, OR>((yyvsp[-2].union_expression_ptr), (yyvsp[0].union_expression_ptr), (INT|DOUBLE));}
#line 1961 "gpl.tab.c" /* yacc.c:1646  */
    break;

  case 93:
#line 609 "gpl.y" /* yacc.c:1646  */
    {(yyval.union_expression_ptr) = Bin_op_check<And, AND>((yyvsp[-2].union_expression_ptr), (yyvsp[0].union_expression_ptr), (INT|DOUBLE));}
#line 1967 "gpl.tab.c" /* yacc.c:1646  */
    break;

  case 94:
#line 610 "gpl.y" /* yacc.c:1646  */
    {(yyval.union_expression_ptr) = Bin_op_check<Less_equal, LESS_EQUAL>((yyvsp[-2].union_expression_ptr), (yyvsp[0].union_expression_ptr), (INT|DOUBLE|STRING));}
#line 1973 "gpl.tab.c" /* yacc.c:1646  */
    break;

  case 95:
#line 611 "gpl.y" /* yacc.c:1646  */
    {(yyval.union_expression_ptr) = Bin_op_check<Greater_equal, GREATER_EQUAL>((yyvsp[-2].union_expression_ptr), (yyvsp[0].union_expression_ptr), (INT|DOUBLE|STRING));}
#line 1979 "gpl.tab.c" /* yacc.c:1646  */
    break;

  case 96:
#line 612 "gpl.y" /* yacc.c:1646  */
    {(yyval.union_expression_ptr) = Bin_op_check<Less_than, LESS_THAN>((yyvsp[-2].union_expression_ptr), (yyvsp[0].union_expression_ptr), (INT|DOUBLE|STRING));}
#line 1985 "gpl.tab.c" /* yacc.c:1646  */
    break;

  case 97:
#line 613 "gpl.y" /* yacc.c:1646  */
    {(yyval.union_expression_ptr) = Bin_op_check<Greater_than, GREATER_THAN>((yyvsp[-2].union_expression_ptr), (yyvsp[0].union_expression_ptr), (INT|DOUBLE|STRING));}
#line 1991 "gpl.tab.c" /* yacc.c:1646  */
    break;

  case 98:
#line 614 "gpl.y" /* yacc.c:1646  */
    {(yyval.union_expression_ptr) = Bin_op_check<Equal, EQUAL>((yyvsp[-2].union_expression_ptr), (yyvsp[0].union_expression_ptr), (INT|DOUBLE|STRING));}
#line 1997 "gpl.tab.c" /* yacc.c:1646  */
    break;

  case 99:
#line 615 "gpl.y" /* yacc.c:1646  */
    {(yyval.union_expression_ptr) = Bin_op_check<Not_equal, NOT_EQUAL>((yyvsp[-2].union_expression_ptr), (yyvsp[0].union_expression_ptr), (INT|DOUBLE|STRING));}
#line 2003 "gpl.tab.c" /* yacc.c:1646  */
    break;

  case 100:
#line 616 "gpl.y" /* yacc.c:1646  */
    {(yyval.union_expression_ptr) = Bin_op_check<Plus, PLUS>((yyvsp[-2].union_expression_ptr), (yyvsp[0].union_expression_ptr), (INT|DOUBLE|STRING));}
#line 2009 "gpl.tab.c" /* yacc.c:1646  */
    break;

  case 101:
#line 617 "gpl.y" /* yacc.c:1646  */
    {(yyval.union_expression_ptr)= Bin_op_check<Minus, MINUS>((yyvsp[-2].union_expression_ptr), (yyvsp[0].union_expression_ptr), (INT|DOUBLE));}
#line 2015 "gpl.tab.c" /* yacc.c:1646  */
    break;

  case 102:
#line 618 "gpl.y" /* yacc.c:1646  */
    {(yyval.union_expression_ptr) = Bin_op_check<Multiply, MULTIPLY>((yyvsp[-2].union_expression_ptr), (yyvsp[0].union_expression_ptr), (INT|DOUBLE));}
#line 2021 "gpl.tab.c" /* yacc.c:1646  */
    break;

  case 103:
#line 620 "gpl.y" /* yacc.c:1646  */
    {
      if(((yyvsp[0].union_expression_ptr)->type()&(INT|DOUBLE)) && ((yyvsp[0].union_expression_ptr)->evaluate()->as_double() == 0 )){
        Error::error(Error::DIVIDE_BY_ZERO_AT_PARSE_TIME);
        delete (yyvsp[0].union_expression_ptr);
        delete (yyvsp[-2].union_expression_ptr);
        (yyval.union_expression_ptr) = new Integer_constant(0);
      }else{
        (yyval.union_expression_ptr) = Bin_op_check<Divide, DIVIDE>((yyvsp[-2].union_expression_ptr), (yyvsp[0].union_expression_ptr), (INT|DOUBLE));
      }
    }
#line 2036 "gpl.tab.c" /* yacc.c:1646  */
    break;

  case 104:
#line 631 "gpl.y" /* yacc.c:1646  */
    {
      if(((yyvsp[0].union_expression_ptr)->type()&(INT)) && ((yyvsp[0].union_expression_ptr)->evaluate()->as_int() == 0 )){
        Error::error(Error::MOD_BY_ZERO_AT_PARSE_TIME);
        delete (yyvsp[0].union_expression_ptr);
        delete (yyvsp[-2].union_expression_ptr);
        (yyval.union_expression_ptr) = new Integer_constant(0);
      }else{
        (yyval.union_expression_ptr) = Bin_op_check<Mod, MOD>((yyvsp[-2].union_expression_ptr), (yyvsp[0].union_expression_ptr), (INT));
      }
    }
#line 2051 "gpl.tab.c" /* yacc.c:1646  */
    break;

  case 105:
#line 641 "gpl.y" /* yacc.c:1646  */
    {(yyval.union_expression_ptr) = Un_op_check<Unary_minus, UNARY_MINUS>((yyvsp[0].union_expression_ptr), (INT|DOUBLE));}
#line 2057 "gpl.tab.c" /* yacc.c:1646  */
    break;

  case 106:
#line 642 "gpl.y" /* yacc.c:1646  */
    {(yyval.union_expression_ptr) = Un_op_check<Not, NOT>((yyvsp[0].union_expression_ptr), (INT|DOUBLE));}
#line 2063 "gpl.tab.c" /* yacc.c:1646  */
    break;

  case 107:
#line 643 "gpl.y" /* yacc.c:1646  */
    {(yyval.union_expression_ptr) = Un_op_check<Sine, SIN>((yyvsp[-1].union_expression_ptr), (INT|DOUBLE));}
#line 2069 "gpl.tab.c" /* yacc.c:1646  */
    break;

  case 108:
#line 644 "gpl.y" /* yacc.c:1646  */
    {(yyval.union_expression_ptr) = Un_op_check<Cosine, COS>((yyvsp[-1].union_expression_ptr), (INT|DOUBLE));}
#line 2075 "gpl.tab.c" /* yacc.c:1646  */
    break;

  case 109:
#line 645 "gpl.y" /* yacc.c:1646  */
    {(yyval.union_expression_ptr) = Un_op_check<Tan, TAN>((yyvsp[-1].union_expression_ptr), (INT|DOUBLE));}
#line 2081 "gpl.tab.c" /* yacc.c:1646  */
    break;

  case 110:
#line 646 "gpl.y" /* yacc.c:1646  */
    {(yyval.union_expression_ptr) = Un_op_check<Asin, ASIN>((yyvsp[-1].union_expression_ptr), (INT|DOUBLE));}
#line 2087 "gpl.tab.c" /* yacc.c:1646  */
    break;

  case 111:
#line 647 "gpl.y" /* yacc.c:1646  */
    {(yyval.union_expression_ptr) = Un_op_check<Acos, ACOS>((yyvsp[-1].union_expression_ptr), (INT|DOUBLE));}
#line 2093 "gpl.tab.c" /* yacc.c:1646  */
    break;

  case 112:
#line 648 "gpl.y" /* yacc.c:1646  */
    {(yyval.union_expression_ptr) = Un_op_check<Atan, ATAN>((yyvsp[-1].union_expression_ptr), (INT|DOUBLE));}
#line 2099 "gpl.tab.c" /* yacc.c:1646  */
    break;

  case 113:
#line 649 "gpl.y" /* yacc.c:1646  */
    {(yyval.union_expression_ptr) = Un_op_check<Sqrt, SQRT>((yyvsp[-1].union_expression_ptr), (INT|DOUBLE));}
#line 2105 "gpl.tab.c" /* yacc.c:1646  */
    break;

  case 114:
#line 650 "gpl.y" /* yacc.c:1646  */
    {(yyval.union_expression_ptr) = Un_op_check<Abs, ABS>((yyvsp[-1].union_expression_ptr), (INT|DOUBLE));}
#line 2111 "gpl.tab.c" /* yacc.c:1646  */
    break;

  case 115:
#line 651 "gpl.y" /* yacc.c:1646  */
    {(yyval.union_expression_ptr) = Un_op_check<Floor, FLOOR>((yyvsp[-1].union_expression_ptr), (INT|DOUBLE));}
#line 2117 "gpl.tab.c" /* yacc.c:1646  */
    break;

  case 116:
#line 652 "gpl.y" /* yacc.c:1646  */
    {(yyval.union_expression_ptr) = Un_op_check<Random, RANDOM>((yyvsp[-1].union_expression_ptr), (INT|DOUBLE));}
#line 2123 "gpl.tab.c" /* yacc.c:1646  */
    break;

  case 117:
#line 653 "gpl.y" /* yacc.c:1646  */
    {(yyval.union_expression_ptr)=nullptr;/*CHANGE*/}
#line 2129 "gpl.tab.c" /* yacc.c:1646  */
    break;

  case 118:
#line 654 "gpl.y" /* yacc.c:1646  */
    {(yyval.union_expression_ptr)=nullptr;/*CHANGE*/}
#line 2135 "gpl.tab.c" /* yacc.c:1646  */
    break;

  case 119:
#line 661 "gpl.y" /* yacc.c:1646  */
    {(yyval.union_expression_ptr)=(yyvsp[-1].union_expression_ptr);}
#line 2141 "gpl.tab.c" /* yacc.c:1646  */
    break;

  case 120:
#line 662 "gpl.y" /* yacc.c:1646  */
    {(yyval.union_expression_ptr) = (yyvsp[0].union_expression_ptr);}
#line 2147 "gpl.tab.c" /* yacc.c:1646  */
    break;

  case 121:
#line 663 "gpl.y" /* yacc.c:1646  */
    {(yyval.union_expression_ptr) = new Integer_constant((yyvsp[0].union_int));}
#line 2153 "gpl.tab.c" /* yacc.c:1646  */
    break;

  case 122:
#line 664 "gpl.y" /* yacc.c:1646  */
    {(yyval.union_expression_ptr) = new Integer_constant(1);}
#line 2159 "gpl.tab.c" /* yacc.c:1646  */
    break;

  case 123:
#line 665 "gpl.y" /* yacc.c:1646  */
    {(yyval.union_expression_ptr) = new Integer_constant(0);}
#line 2165 "gpl.tab.c" /* yacc.c:1646  */
    break;

  case 124:
#line 666 "gpl.y" /* yacc.c:1646  */
    {(yyval.union_expression_ptr) = new Double_constant((yyvsp[0].union_double));}
#line 2171 "gpl.tab.c" /* yacc.c:1646  */
    break;

  case 125:
#line 667 "gpl.y" /* yacc.c:1646  */
    {(yyval.union_expression_ptr) = new String_constant(*(yyvsp[0].union_string)); delete (yyvsp[0].union_string);}
#line 2177 "gpl.tab.c" /* yacc.c:1646  */
    break;


#line 2181 "gpl.tab.c" /* yacc.c:1646  */
      default: break;
    }
  /* User semantic actions sometimes alter yychar, and that requires
     that yytoken be updated with the new translation.  We take the
     approach of translating immediately before every use of yytoken.
     One alternative is translating here after every semantic action,
     but that translation would be missed if the semantic action invokes
     YYABORT, YYACCEPT, or YYERROR immediately after altering yychar or
     if it invokes YYBACKUP.  In the case of YYABORT or YYACCEPT, an
     incorrect destructor might then be invoked immediately.  In the
     case of YYERROR or YYBACKUP, subsequent parser actions might lead
     to an incorrect destructor call or verbose syntax error message
     before the lookahead is translated.  */
  YY_SYMBOL_PRINT ("-> $$ =", yyr1[yyn], &yyval, &yyloc);

  YYPOPSTACK (yylen);
  yylen = 0;
  YY_STACK_PRINT (yyss, yyssp);

  *++yyvsp = yyval;

  /* Now 'shift' the result of the reduction.  Determine what state
     that goes to, based on the state we popped back to and the rule
     number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTOKENS] + *yyssp;
  if (0 <= yystate && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTOKENS];

  goto yynewstate;


/*--------------------------------------.
| yyerrlab -- here on detecting error.  |
`--------------------------------------*/
yyerrlab:
  /* Make sure we have latest lookahead translation.  See comments at
     user semantic actions for why this is necessary.  */
  yytoken = yychar == YYEMPTY ? YYEMPTY : YYTRANSLATE (yychar);

  /* If not already recovering from an error, report this error.  */
  if (!yyerrstatus)
    {
      ++yynerrs;
#if ! YYERROR_VERBOSE
      yyerror (YY_("syntax error"));
#else
# define YYSYNTAX_ERROR yysyntax_error (&yymsg_alloc, &yymsg, \
                                        yyssp, yytoken)
      {
        char const *yymsgp = YY_("syntax error");
        int yysyntax_error_status;
        yysyntax_error_status = YYSYNTAX_ERROR;
        if (yysyntax_error_status == 0)
          yymsgp = yymsg;
        else if (yysyntax_error_status == 1)
          {
            if (yymsg != yymsgbuf)
              YYSTACK_FREE (yymsg);
            yymsg = (char *) YYSTACK_ALLOC (yymsg_alloc);
            if (!yymsg)
              {
                yymsg = yymsgbuf;
                yymsg_alloc = sizeof yymsgbuf;
                yysyntax_error_status = 2;
              }
            else
              {
                yysyntax_error_status = YYSYNTAX_ERROR;
                yymsgp = yymsg;
              }
          }
        yyerror (yymsgp);
        if (yysyntax_error_status == 2)
          goto yyexhaustedlab;
      }
# undef YYSYNTAX_ERROR
#endif
    }



  if (yyerrstatus == 3)
    {
      /* If just tried and failed to reuse lookahead token after an
         error, discard it.  */

      if (yychar <= YYEOF)
        {
          /* Return failure if at end of input.  */
          if (yychar == YYEOF)
            YYABORT;
        }
      else
        {
          yydestruct ("Error: discarding",
                      yytoken, &yylval);
          yychar = YYEMPTY;
        }
    }

  /* Else will try to reuse lookahead token after shifting the error
     token.  */
  goto yyerrlab1;


/*---------------------------------------------------.
| yyerrorlab -- error raised explicitly by YYERROR.  |
`---------------------------------------------------*/
yyerrorlab:

  /* Pacify compilers like GCC when the user code never invokes
     YYERROR and the label yyerrorlab therefore never appears in user
     code.  */
  if (/*CONSTCOND*/ 0)
     goto yyerrorlab;

  /* Do not reclaim the symbols of the rule whose action triggered
     this YYERROR.  */
  YYPOPSTACK (yylen);
  yylen = 0;
  YY_STACK_PRINT (yyss, yyssp);
  yystate = *yyssp;
  goto yyerrlab1;


/*-------------------------------------------------------------.
| yyerrlab1 -- common code for both syntax error and YYERROR.  |
`-------------------------------------------------------------*/
yyerrlab1:
  yyerrstatus = 3;      /* Each real token shifted decrements this.  */

  for (;;)
    {
      yyn = yypact[yystate];
      if (!yypact_value_is_default (yyn))
        {
          yyn += YYTERROR;
          if (0 <= yyn && yyn <= YYLAST && yycheck[yyn] == YYTERROR)
            {
              yyn = yytable[yyn];
              if (0 < yyn)
                break;
            }
        }

      /* Pop the current state because it cannot handle the error token.  */
      if (yyssp == yyss)
        YYABORT;


      yydestruct ("Error: popping",
                  yystos[yystate], yyvsp);
      YYPOPSTACK (1);
      yystate = *yyssp;
      YY_STACK_PRINT (yyss, yyssp);
    }

  YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
  *++yyvsp = yylval;
  YY_IGNORE_MAYBE_UNINITIALIZED_END


  /* Shift the error token.  */
  YY_SYMBOL_PRINT ("Shifting", yystos[yyn], yyvsp, yylsp);

  yystate = yyn;
  goto yynewstate;


/*-------------------------------------.
| yyacceptlab -- YYACCEPT comes here.  |
`-------------------------------------*/
yyacceptlab:
  yyresult = 0;
  goto yyreturn;

/*-----------------------------------.
| yyabortlab -- YYABORT comes here.  |
`-----------------------------------*/
yyabortlab:
  yyresult = 1;
  goto yyreturn;

#if !defined yyoverflow || YYERROR_VERBOSE
/*-------------------------------------------------.
| yyexhaustedlab -- memory exhaustion comes here.  |
`-------------------------------------------------*/
yyexhaustedlab:
  yyerror (YY_("memory exhausted"));
  yyresult = 2;
  /* Fall through.  */
#endif

yyreturn:
  if (yychar != YYEMPTY)
    {
      /* Make sure we have latest lookahead translation.  See comments at
         user semantic actions for why this is necessary.  */
      yytoken = YYTRANSLATE (yychar);
      yydestruct ("Cleanup: discarding lookahead",
                  yytoken, &yylval);
    }
  /* Do not reclaim the symbols of the rule whose action triggered
     this YYABORT or YYACCEPT.  */
  YYPOPSTACK (yylen);
  YY_STACK_PRINT (yyss, yyssp);
  while (yyssp != yyss)
    {
      yydestruct ("Cleanup: popping",
                  yystos[*yyssp], yyvsp);
      YYPOPSTACK (1);
    }
#ifndef yyoverflow
  if (yyss != yyssa)
    YYSTACK_FREE (yyss);
#endif
#if YYERROR_VERBOSE
  if (yymsg != yymsgbuf)
    YYSTACK_FREE (yymsg);
#endif
  return yyresult;
}
#line 675 "gpl.y" /* yacc.c:1906  */

